/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StationsRouteImport } from './routes/_stations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationsStationsRouteImport } from './routes/_stations.stations'
import { Route as StationsStationsIdRouteImport } from './routes/_stations.stations_.$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsRoute = StationsRouteImport.update({
  id: '/_stations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsStationsRoute = StationsStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => StationsRoute,
} as any)
const StationsStationsIdRoute = StationsStationsIdRouteImport.update({
  id: '/stations_/$id',
  path: '/stations/$id',
  getParentRoute: () => StationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/stations': typeof StationsStationsRoute
  '/stations/$id': typeof StationsStationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/stations': typeof StationsStationsRoute
  '/stations/$id': typeof StationsStationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_stations': typeof StationsRouteWithChildren
  '/about': typeof AboutRoute
  '/_stations/stations': typeof StationsStationsRoute
  '/_stations/stations_/$id': typeof StationsStationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/stations' | '/stations/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/stations' | '/stations/$id'
  id:
    | '__root__'
    | '/'
    | '/_stations'
    | '/about'
    | '/_stations/stations'
    | '/_stations/stations_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StationsRoute: typeof StationsRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_stations': {
      id: '/_stations'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_stations/stations': {
      id: '/_stations/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsStationsRouteImport
      parentRoute: typeof StationsRoute
    }
    '/_stations/stations_/$id': {
      id: '/_stations/stations_/$id'
      path: '/stations/$id'
      fullPath: '/stations/$id'
      preLoaderRoute: typeof StationsStationsIdRouteImport
      parentRoute: typeof StationsRoute
    }
  }
}

interface StationsRouteChildren {
  StationsStationsRoute: typeof StationsStationsRoute
  StationsStationsIdRoute: typeof StationsStationsIdRoute
}

const StationsRouteChildren: StationsRouteChildren = {
  StationsStationsRoute: StationsStationsRoute,
  StationsStationsIdRoute: StationsStationsIdRoute,
}

const StationsRouteWithChildren = StationsRoute._addFileChildren(
  StationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StationsRoute: StationsRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
